name: 'Simple PHP Build Action'
author: Milan1750
description: 'Build PHP app using Composer.'
inputs:
  generate-zip:
    description: 'Generate package zip file?'
    default: false
outputs:
  path:
    description: 'Build path'
  zip_path:
    description: 'Zip file path'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.generate-zip }}
branding:
  icon: 'upload-cloud'
  color: 'blue'
